<?php
<<<<<<< HEAD
$html = '<section class="sectionAcceuilHaut">';
$html .= '<div class="flex flex-col justify-center items-center my-10">';
$html .= '<img class="logo" src="images/New_Elegant_Logo1.jpg">';

$html .= '<h1 class="text-4xl text-blue-900 font-bold mt-10"> Bienvenue chez Cé Beauté </h1>';
$html .= '<h2 class="text-3xl text-blue-900 font-semibold border border-blue-900 rounded-full py-5 px-10 mt-10 mb-5">Horaires</h2>';
$html .= '<div class="flex items-center mt-5">';
$html .= '<i class="fas fa-calendar-alt text-blue-900 mr-5"></i>';
$html .= '<p class="text-xl text-blue-900">Du lundi au vendredi 9h - 19h</p>';
$html .= '</div>';
$html .= '<p class="text-xl text-blue-900">Samedi 9h - 16h</p>';
$html .= '<div class="flex items-center mt-5">';
$html .= '<i class="fas fa-map-marker-alt text-blue-900 mr-5"></i>';
$html .= '<p class="text-xl text-blue-900">Saint-léger-de-linières et ses alentours</p>';
$html .= '</div>';
$html .= '<div class="flex items-center mt-5">';
$html .= '<i class="fas fa-phone text-blue-900 mr-5"></i>';
$html .= '<p class="text-xl text-blue-900">06 71 43 04 16</p>';
$html .= '</div>';
$html .= '</div>';
$html .= '   <div class="swiper mySwiper">';
$html .= ' <div class="swiper-wrapper">';
$html .= ' <div class="swiper-slide" id="sliderUn">';
$html .= '  <h2> Direction longlerie </h2>';
$html .= '  <p> specialiste des chansons </p>';
$html .= '  <p> specialiste des chansons </p>';
$html .= ' </div>';
$html .= ' <div class="swiper-slide">';
$html .= '   <img src="https://swiperjs.com/demos/images/nature-2.jpg" />';
$html .= ' </div>';
$html .= ' <div class="swiper-slide">';
$html .= '   <img src="https://swiperjs.com/demos/images/nature-3.jpg" />';
$html .= ' </div>';
$html .= ' <div class="swiper-slide">';
$html .= '   <img src="https://swiperjs.com/demos/images/nature-4.jpg" />';
$html .= ' </div>';
$html .= ' <div class="swiper-slide">';
$html .= '   <img src="https://swiperjs.com/demos/images/nature-5.jpg" />';
$html .= '  </div>';
$html .= ' <div class="swiper-slide">';
$html .= '   <img src="https://swiperjs.com/demos/images/nature-6.jpg" />';
$html .= ' </div>';
$html .= ' <div class="swiper-slide">';
$html .= '   <img src="https://swiperjs.com/demos/images/nature-7.jpg" />';
$html .= ' </div>';
$html .= ' <div class="swiper-slide">';
$html .= '   <img src="https://swiperjs.com/demos/images/nature-8.jpg" />';
$html .= ' </div>';
$html .= ' <div class="swiper-slide">';
$html .= '   <img src="https://swiperjs.com/demos/images/nature-9.jpg" />';
$html .= '  </div>';
$html .= '</div>';
// $html.= ' <div class="swiper-pagination"></div>';
$html .= '</div>';
$html .= '<a href="#sectionAcceuilBas" class="btnAcceuilBas "><p class="text-4xl text-center"> v </p></a>';
$html .= '</section>';
$html .= '<section id="sectionAcceuilBas">';
$html .= '<div class="presentation grid grid-cols-2 my-10 gap-x-20">';
$html .= '<div class="flex justify-center items-center">';
$html .= '<img src="images/New_Elegant_Logo1.jpg" class="photoProfil">';
$html .= '</div>';
$html .= '<div class="flex justify-center items-center">';
$html .= '<p>petite presentation </p>';
$html .= '</div>';
$html .= '</div>';

$html .= '<h2> Mon parcours </h2>';
$html .= '<div class="parcours grid grid-cols-2 my-10">';
$html .= '<div class=" parcoursDiv flex items-center border-r-2 border-blue-600 justify-end">';
$html .= '<p class="mr-8">petite presentation </p>';
$html .= '</div>';
$html .= '<div class="parcoursDiv flex items-center border-l-2 border-blue-600 justify-start">';
$html .= '<p></p>';
$html .= '</div>';
$html .= '<div class=" parcoursDiv flex items-center border-r-2 border-blue-600 justify-end">';
$html .= '<p></p>';
$html .= '</div>';
$html .= '<div class="parcoursDiv flex items-center border-l-2 border-blue-600 justify-start ">';
$html .= '<p class="ml-8">petite presentation </p>';
$html .= '</div>';
$html .= '<div class=" parcoursDiv flex items-center border-r-2 border-blue-600 justify-end">';
$html .= '<p class="mr-8">petite presentation </p>';
$html .= '</div>';
$html .= '<div class="parcoursDiv flex items-center border-l-2 border-blue-600 justify-start">';
$html .= '<p></p>';
$html .= '</div>';
$html .= '<div class="parcoursDiv flex items-center border-r-2 border-blue-600 justify-end">';
$html .= '<p></p>';
$html .= '</div>';
$html .= '<div class="parcoursDiv flex items-center border-l-2 border-blue-600 justify-start">';
$html .= '<p class="ml-8">petite presentation </p>';
$html .= '</div>';
$html .= '</div>';
$html .= '</section>';
$html .= '<script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>';
$html .= '<script src="js/accueil.js"></script>';
=======
    $html='<section class="sectionAcceuilHaut">';
    $html.='<div class="flex flex-col justify-center items-center my-5">';
    $html.='<img class="logo" src="images/New_Elegant_Logo1.jpg">';
    
    $html.='<h1 class="h1Acceuil text-2xl"> Bienvenu chez CéBeauté </h1>';
    $html.='</div>';
    $html.= '   <div class="swiper mySwiper">';
    $html.= ' <div class="swiper-wrapper">';
    $html.= ' <div class="swiper-slide" id="sliderUn">';
    $html.= '  <h2> Direction longlerie </h2>';
    $html.= '  <p> specialiste des chansons </p>';
    $html.= '  <p> specialiste des chansons </p>';
    $html.= ' </div>';
    $html.= ' <div class="swiper-slide">';
    $html.= '   <img src="https://swiperjs.com/demos/images/nature-2.jpg" />';
    $html.= ' </div>';
    $html.= ' <div class="swiper-slide">';
    $html.= '   <img src="https://swiperjs.com/demos/images/nature-3.jpg" />';
    $html.= ' </div>';
    $html.= ' <div class="swiper-slide">';
    $html.= '   <img src="https://swiperjs.com/demos/images/nature-4.jpg" />';
    $html.= ' </div>';
    $html.= ' <div class="swiper-slide">';
    $html.= '   <img src="https://swiperjs.com/demos/images/nature-5.jpg" />';
    $html.= '  </div>';
    $html.= ' <div class="swiper-slide">';
    $html.= '   <img src="https://swiperjs.com/demos/images/nature-6.jpg" />';
    $html.= ' </div>';
    $html.= ' <div class="swiper-slide">';
    $html.= '   <img src="https://swiperjs.com/demos/images/nature-7.jpg" />';
    $html.= ' </div>';
    $html.= ' <div class="swiper-slide">';
    $html.= '   <img src="https://swiperjs.com/demos/images/nature-8.jpg" />';
    $html.= ' </div>';
    $html.= ' <div class="swiper-slide">';
    $html.= '   <img src="https://swiperjs.com/demos/images/nature-9.jpg" />';
    $html.= '  </div>';
    $html.= '</div>';
   // $html.= ' <div class="swiper-pagination"></div>';
    $html.= '</div>';
    $html.= '<a href="#sectionAcceuilBas" class="btnAcceuilBas"><p class="text-4xl text-center"> v </p></a>';
    $html.='</section >';
    $html.='<section id="sectionAcceuilBas">';
    $html.='<div class="presentation grid grid-cols-2 my-10 gap-x-20">';
    $html.='<div class="flex justify-center items-center">';
    $html.='<img src="images/New_Elegant_Logo1.jpg" class="photoProfil">';
    $html.='</div>';
    $html.='<div class="flex justify-center items-center">';
    $html.='<p>petite presentation </p>';
    $html.='</div>';
    $html.='</div>';

    $html.='<h2> Mon parcours </h2>';
    $html.='<div class="parcours grid grid-cols-2 my-10">';
    $html.='<div class=" parcoursDiv flex items-center border-r-2 border-blue-600 justify-end">';
    $html.='<p class="mr-8">petite presentation </p>';
    $html.='</div>';
    $html.='<div class="parcoursDiv flex items-center border-l-2 border-blue-600 justify-start">';
    $html.='<p></p>';
    $html.='</div>';
    $html.='<div class=" parcoursDiv flex items-center border-r-2 border-blue-600 justify-end">';
    $html.='<p></p>';
    $html.='</div>';
    $html.='<div class="parcoursDiv flex items-center border-l-2 border-blue-600 justify-start ">';
    $html.='<p class="ml-8">petite presentation </p>';
    $html.='</div>';
    $html.='<div class=" parcoursDiv flex items-center border-r-2 border-blue-600 justify-end">';
    $html.='<p class="mr-8">petite presentation </p>';
    $html.='</div>';
    $html.='<div class="parcoursDiv flex items-center border-l-2 border-blue-600 justify-start">';
    $html.='<p></p>';
    $html.='</div>';
    $html.='<div class="parcoursDiv flex items-center border-r-2 border-blue-600 justify-end">';
    $html.='<p></p>';
    $html.='</div>';
    $html.='<div class="parcoursDiv flex items-center border-l-2 border-blue-600 justify-start">';
    $html.='<p class="ml-8">petite presentation </p>';
    $html.='</div>';
    $html.='</div>';
    $html.='</section>';
    $html.='<script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>';
    $html.='<script src="js/accueil.js"></script>';
>>>>>>> 965fb93f6771bd4931895a3a2c85ceb30c66fde0
