<?php
$html = '<section class="sectionAcceuilHaut">';
$html .= '<div class="flex flex-col justify-center items-center my-5">';
$html .= '<img class="logo" src="images/New_Elegant_Logo1.jpg">';

$html .= '<h1 class="h1Acceuil text-2xl"> Bienvenu chez CéBeauté </h1>';
$html .= '</div>';
$html .= '   <div class="swiper mySwiper">';
$html .= ' <div class="swiper-wrapper">';
$html .= ' <div class="swiper-slide" id="sliderUn">';
$html .= '  <h2> Direction longlerie </h2>';
$html .= '  <p> specialiste des chansons </p>';
$html .= '  <p> specialiste des chansons </p>';
$html .= ' </div>';
$html .= ' <div class="swiper-slide">';
$html .= '   <img src="https://swiperjs.com/demos/images/nature-2.jpg" />';
$html .= ' </div>';
$html .= ' <div class="swiper-slide">';
$html .= '   <img src="https://swiperjs.com/demos/images/nature-3.jpg" />';
$html .= ' </div>';
$html .= ' <div class="swiper-slide">';
$html .= '   <img src="https://swiperjs.com/demos/images/nature-4.jpg" />';
$html .= ' </div>';
$html .= ' <div class="swiper-slide">';
$html .= '   <img src="https://swiperjs.com/demos/images/nature-5.jpg" />';
$html .= '  </div>';
$html .= ' <div class="swiper-slide">';
$html .= '   <img src="https://swiperjs.com/demos/images/nature-6.jpg" />';
$html .= ' </div>';
$html .= ' <div class="swiper-slide">';
$html .= '   <img src="https://swiperjs.com/demos/images/nature-7.jpg" />';
$html .= ' </div>';
$html .= ' <div class="swiper-slide">';
$html .= '   <img src="https://swiperjs.com/demos/images/nature-8.jpg" />';
$html .= ' </div>';
$html .= ' <div class="swiper-slide">';
$html .= '   <img src="https://swiperjs.com/demos/images/nature-9.jpg" />';
$html .= '  </div>';
$html .= '</div>';
// $html.= ' <div class="swiper-pagination"></div>';
$html .= '</div>';
$html .= '<a href="#sectionAcceuilBas" class="btnAcceuilBas"><p class="text-4xl text-center"> v </p></a>';
$html .= '</section >';
$html .= '<section id="sectionAcceuilBas">';
$html .= '<div class="presentation grid grid-cols-2 my-10 gap-x-20">';
$html .= '<div class="flex justify-center items-center">';
$html .= '<img src="images/New_Elegant_Logo1.jpg" class="photoProfil">';
$html .= '</div>';
$html .= '<div class="flex justify-center items-center">';
$html .= '<p>petite presentation </p>';
$html .= '</div>';
$html .= '</div>';

$html .= '<h2> Mon parcours </h2>';
$html .= '<div class="parcours grid grid-cols-2 my-10">';
$html .= '<div class=" parcoursDiv flex items-center border-r-2 border-blue-600 justify-end">';
$html .= '<p class="mr-8">petite presentation </p>';
$html .= '</div>';
$html .= '<div class="parcoursDiv flex items-center border-l-2 border-blue-600 justify-start">';
$html .= '<p></p>';
$html .= '</div>';
$html .= '<div class=" parcoursDiv flex items-center border-r-2 border-blue-600 justify-end">';
$html .= '<p></p>';
$html .= '</div>';
$html .= '<div class="parcoursDiv flex items-center border-l-2 border-blue-600 justify-start ">';
$html .= '<p class="ml-8">petite presentation </p>';
$html .= '</div>';
$html .= '<div class=" parcoursDiv flex items-center border-r-2 border-blue-600 justify-end">';
$html .= '<p class="mr-8">petite presentation </p>';
$html .= '</div>';
$html .= '<div class="parcoursDiv flex items-center border-l-2 border-blue-600 justify-start">';
$html .= '<p></p>';
$html .= '</div>';
$html .= '<div class="parcoursDiv flex items-center border-r-2 border-blue-600 justify-end">';
$html .= '<p></p>';
$html .= '</div>';
$html .= '<div class="parcoursDiv flex items-center border-l-2 border-blue-600 justify-start">';
$html .= '<p class="ml-8">petite presentation </p>';
$html .= '</div>';
$html .= '</div>';
$html .= '</section>';
$html .= '<script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>';
$html .= '<script src="js/accueil.js"></script>';
?>
